# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56937dce2332593d5272c0bace5f1e5db0e5557517df518127fd52a93bde8d3507d3e129b0df950dab62ca95a41eedf74483ae0dd2a6d5eb97274783b6b613c1

test:
  secret_key_base: 7eb0656cd77eb731ea0e27e6acb52d8a0dc555e2eff0c05dd891051945319108f31219be7d8a54f3db0e9c076dcd9875ee9f09c4690f7fea15dca72a4fd8333a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
